hc_nodes:
  hosts:
    host1:
      # Blacklist multipath devices which are used for gluster bricks
      # If you omit blacklist_mpath_devices it means all device will be whitelisted.
      # If the disks are not blacklisted, and then its taken that multipath configuration
      # exists in the server and one should provide /dev/mapper/<WWID> instead of /dev/sdx
      blacklist_mpath_devices:
        - sdb
        - sdc

      gluster_infra_luks_devices:
        - devicename: /dev/sdb
          passphrase: test123
        - devicename: /dev/sdc
          passphrase: test1234

      rootpassphrase: <rootpassphrase for host1>
      rootdevice: <Root Device Name>
      networkinterface: <Network interface to bind tang servers>

    host2:
      # Blacklist multipath devices which are used for gluster bricks
      # If you omit blacklist_mpath_devices it means all device will be whitelisted.
      # If the disks are not blacklisted, and then its taken that multipath configuration
      # exists in the server and one should provide /dev/mapper/<WWID> instead of /dev/sdx
      blacklist_mpath_devices:
        - sdb
        - sdc

      gluster_infra_luks_devices:
        - devicename: /dev/sdb
          passphrase: test123
        - devicename: /dev/sdc
          passphrase: test1234

      rootpassphrase: <rootpassphrase for host2>
      rootdevice: <Root Device Name>
      networkinterface: <Network interface to bind tang servers>

    host3:
      # Blacklist multipath devices which are used for gluster bricks
      # If you omit blacklist_mpath_devices it means all device will be whitelisted.
      # If the disks are not blacklisted, and then its taken that multipath configuration
      # exists in the server and one should provide /dev/mapper/<WWID> instead of /dev/sdx
      blacklist_mpath_devices:
        - sdb
        - sdc

      gluster_infra_luks_devices:
        - devicename: /dev/sdd
          passphrase: test123
        - devicename: /dev/sde
          passphrase: test1234

      rootpassphrase: <rootpassphrase for host3>
      rootdevice: <Root Device Name>
      networkinterface: <Network interface to bind tang servers>

  vars:
    gluster_infra_tangservers:
      - url: http://<tang server ipaddress>
      - url: http://<tang server ipaddress>
